# ==========================================
# Configuraci\u00f3n de Microservicios FilmTracker
# ==========================================

# Entorno de Desarrollo (Local)
api.shows.url=http://localhost:3001/api/shows
api.users.url=http://localhost:3002/api/users
api.auth.url=http://localhost:3003/api/auth
api.library.url=http://localhost:3004/api
api.reviews.url=http://localhost:3005/api
api.friends.url=http://localhost:3006/api
